## R 연습(2장 : 자료형)

### 1. 상수(atomic) 데이터 객체

* `double(float)`

In [5]:
typeof(10)

[1] "double"

> R에서는 허수가 아닌 모든 수를 실수로 선언한다.

* `integer`

In [7]:
typeof(10L)  ## L을 붙여야 정수형으로 받아들임(f의 반대)

[1] "integer"

*  character(string)

In [8]:
typeof("string")
typeof('character')

[1] "character"

[1] "character"

* logical(bool)

In [9]:
typeof(2 < 4)

[1] "logical"

### 2. 벡터(vector) 데이터 객체

- 하나 이상의 원소로 이뤄져 있으며, 각 원소는 타입이 동일해진다.

In [13]:
x1 <- c(1,2,3,4)  ## Double vector
x2 <- c("Aaa", "Bbb", "Ccc")  ## Character vector
x3 <- 10:15  ## Create seqence vector ; 파이썬과 다르게 끝 정수까지 포함하여 수열 생성
y <- c(x1, 0, x2)  ## Binding serveral vectors

print(c(x1, x2, x3, y))  ## 결합된 벡터의 자료형이 character로 변환됨

 [1] "1"   "2"   "3"   "4"   "Aaa" "Bbb" "Ccc" "10"  "11"  "12"  "13"  "14" 
[13] "15"  "1"   "2"   "3"   "4"   "0"   "Aaa" "Bbb" "Ccc"


* `rep`(repeat) : 같은 수의 반복

In [21]:
print(rep(2, 10))
print(rep(c(1, 2), each = 5))  ## each를 활용하여 벡터의 각 원소마다 반복 횟수를 지정

 [1] 2 2 2 2 2 2 2 2 2 2
 [1] 1 1 1 1 1 2 2 2 2 2


* `seq`(sequence) : 등차 수열

In [23]:
print(seq(0, 1, length = 11))
print(seq(0, 1, by = 0.1))

 [1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0
 [1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0


* 자료형을 벡터로 할당

In [27]:
character(length = 10)

[1] "" "" "" "" "" "" "" "" "" ""

In [29]:
double(10)

[1] 0 0 0 0 0 0 0 0 0 0

In [30]:
logical(10)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

* 벡터의 클래스

> `numeric` : 연속형
> 
> `factor` : 범주형
> 
> `ordered` : 순서있는 범주형

In [38]:
factor(1:10)

[1] 1  2  3  4  5  6  7  8  9  10
Levels: 1 2 3 4 5 6 7 8 9 10

* 벡터의 이용

In [57]:
x <- c(1, 10, 7)
print(x[c(2:3)])  ## 2~3번째 인덱스 원소를 호출

y <- c(a = 1, b = 10, c = 7)  ## 컴포넌트 이름 지정
print(y[c("a", "c")])

[1] 10  7
a c 
1 7 


### 3. 행렬(matrix) 데이터 객채

In [46]:
A <- matrix(c(2,12,5,6,3,31,13,35,5,5,7,72), ncol=3); A

[,1] [,2] [,3]
[1,]  2    3    5  
[2,] 12   31    5  
[3,]  5   13    7  
[4,]  6   35   72

In [47]:
X1 <- diag(1, 5); X1

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    1    0    0    0   
[3,] 0    0    1    0    0   
[4,] 0    0    0    1    0   
[5,] 0    0    0    0    1

In [48]:
diag(X1)  ## 대각원소의 추출

[1] 1 1 1 1 1

In [52]:
x <- c(1, 2, 3); y <- c(4,5,6)
print(rbind(x, y))  ## row bind
print(cbind(x, y))  ## column bind

  [,1] [,2] [,3]
x    1    2    3
y    4    5    6
     x y
[1,] 1 4
[2,] 2 5
[3,] 3 6


In [53]:
x <- matrix(c(1:6), ncol = 3)
y <- matrix(c(1, -1, 2, 3, 2, -1), ncol = 3)

x*y  ## 행렬 원소간 곱(행렬곱이 아님)

[,1] [,2] [,3]
[1,]  1    6   10  
[2,] -2   12   -6

In [54]:
t(x)

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [55]:
x%*%t(y)  ## 행렬 곱

[,1] [,2]
[1,] 17   3   
[2,] 22   4

In [56]:
solve(x%*%t(y))  ## 역행렬

[,1] [,2]
[1,]   2  -1.5
[2,] -11   8.5

### 4. 리스트(list)

In [62]:
Lst <- list(name = "John", wife = "Jane", child.ages = c(4, 5, 11))
Lst

$name
[1] "John"

$wife
[1] "Jane"

$child.ages
[1]  4  5 11

* 리스트의 원소에 접근하는 법

In [73]:
print(Lst[1])
print(Lst["name"])

$name
[1] "John"

$name
[1] "John"



In [74]:
print(Lst[[1]])
print(Lst[["name"]])
print(Lst$name)

[1] "John"
[1] "John"
[1] "John"


In [79]:
lst <- Lst[2:3]
lst[1]

$wife
[1] "Jane"

* `length()` 함수

In [80]:
length(Lst) + length(lst)

[1] 5

* 리스트의 결합(벡터의 결합과 동일)